load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "visibility_polygon",
    srcs = ["visibility_polygon.cc"],
    hdrs = [
        "geometry.hh",
        "visibility_polygon.hh",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "utility",
    hdrs = [
        "utility.hh",
    ],
    visibility = ["//visibility:public"],
)
