load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "visibility_polygon",
    srcs = ["visibility_polygon.cc"],
    hdrs = ["visibility_polygon.hh"],
    visibility = ["//visibility:public"],
)
